# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'positioner.ui'
#
# Created: Wed Aug  5 12:46:08 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(692, 355)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.desGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.desGroupBox.setObjectName(_fromUtf8("desGroupBox"))
        self.formLayout = QtGui.QFormLayout(self.desGroupBox)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.desGroupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.xPosTextEntry = QtGui.QLineEdit(self.desGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xPosTextEntry.sizePolicy().hasHeightForWidth())
        self.xPosTextEntry.setSizePolicy(sizePolicy)
        self.xPosTextEntry.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(13)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.xPosTextEntry.setFont(font)
        self.xPosTextEntry.setText(_fromUtf8(""))
        self.xPosTextEntry.setProperty("channel", _fromUtf8("MOTOR:1:VAL"))
        self.xPosTextEntry.setObjectName(_fromUtf8("xPosTextEntry"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.xPosTextEntry)
        self.label_2 = QtGui.QLabel(self.desGroupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.yPosTextEntry = QtGui.QLineEdit(self.desGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yPosTextEntry.sizePolicy().hasHeightForWidth())
        self.yPosTextEntry.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(13)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.yPosTextEntry.setFont(font)
        self.yPosTextEntry.setText(_fromUtf8(""))
        self.yPosTextEntry.setProperty("channel", _fromUtf8("MOTOR:1:VAL"))
        self.yPosTextEntry.setObjectName(_fromUtf8("yPosTextEntry"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.yPosTextEntry)
        self.label_3 = QtGui.QLabel(self.desGroupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.zPosTextEntry = QtGui.QLineEdit(self.desGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zPosTextEntry.sizePolicy().hasHeightForWidth())
        self.zPosTextEntry.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(13)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.zPosTextEntry.setFont(font)
        self.zPosTextEntry.setText(_fromUtf8(""))
        self.zPosTextEntry.setProperty("channel", _fromUtf8("MOTOR:1:VAL"))
        self.zPosTextEntry.setObjectName(_fromUtf8("zPosTextEntry"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.zPosTextEntry)
        self.horizontalLayout.addWidget(self.desGroupBox)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout_4 = QtGui.QFormLayout(self.groupBox)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_10)
        self.motor1DesLabel = QtGui.QLabel(self.groupBox)
        self.motor1DesLabel.setObjectName(_fromUtf8("motor1DesLabel"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.motor1DesLabel)
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_11)
        self.motor2DesLabel = QtGui.QLabel(self.groupBox)
        self.motor2DesLabel.setObjectName(_fromUtf8("motor2DesLabel"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.motor2DesLabel)
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_12)
        self.motor3DesLabel = QtGui.QLabel(self.groupBox)
        self.motor3DesLabel.setObjectName(_fromUtf8("motor3DesLabel"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.motor3DesLabel)
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout.addWidget(self.pushButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.desGroupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.desGroupBox_2.setObjectName(_fromUtf8("desGroupBox_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.desGroupBox_2)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_4 = QtGui.QLabel(self.desGroupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtGui.QLabel(self.desGroupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtGui.QLabel(self.desGroupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_6)
        self.motor1ReadbackLabel = QtGui.QLabel(self.desGroupBox_2)
        self.motor1ReadbackLabel.setObjectName(_fromUtf8("motor1ReadbackLabel"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.motor1ReadbackLabel)
        self.motor2ReadbackLabel = QtGui.QLabel(self.desGroupBox_2)
        self.motor2ReadbackLabel.setObjectName(_fromUtf8("motor2ReadbackLabel"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.motor2ReadbackLabel)
        self.motor3ReadbackLabel = QtGui.QLabel(self.desGroupBox_2)
        self.motor3ReadbackLabel.setObjectName(_fromUtf8("motor3ReadbackLabel"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.motor3ReadbackLabel)
        self.horizontalLayout_2.addWidget(self.desGroupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 692, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Positioner Demo", None))
        self.desGroupBox.setTitle(_translate("MainWindow", "Desired Position", None))
        self.label.setText(_translate("MainWindow", "X Position (mm)", None))
        self.xPosTextEntry.setPlaceholderText(_translate("MainWindow", "Enter Value", None))
        self.label_2.setText(_translate("MainWindow", "Y Position (mm)", None))
        self.yPosTextEntry.setPlaceholderText(_translate("MainWindow", "Enter Value", None))
        self.label_3.setText(_translate("MainWindow", "Theta Position (mrad)", None))
        self.zPosTextEntry.setPlaceholderText(_translate("MainWindow", "Enter Value", None))
        self.groupBox.setTitle(_translate("MainWindow", "Desired Motor Values ", None))
        self.label_10.setText(_translate("MainWindow", "MOTOR:1", None))
        self.motor1DesLabel.setText(_translate("MainWindow", "TextLabel", None))
        self.label_11.setText(_translate("MainWindow", "MOTOR:2", None))
        self.motor2DesLabel.setText(_translate("MainWindow", "TextLabel", None))
        self.label_12.setText(_translate("MainWindow", "MOTOR:3", None))
        self.motor3DesLabel.setText(_translate("MainWindow", "TextLabel", None))
        self.pushButton.setText(_translate("MainWindow", "Move Motors To Desired Position", None))
        self.desGroupBox_2.setTitle(_translate("MainWindow", "Motor Readback Values", None))
        self.label_4.setText(_translate("MainWindow", "MOTOR:1:VAL", None))
        self.label_5.setText(_translate("MainWindow", "MOTOR:2:VAL", None))
        self.label_6.setText(_translate("MainWindow", "MOTOR:3:VAL", None))
        self.motor1ReadbackLabel.setText(_translate("MainWindow", "Disconnected", None))
        self.motor2ReadbackLabel.setText(_translate("MainWindow", "Disconnected", None))
        self.motor3ReadbackLabel.setText(_translate("MainWindow", "Disconnected", None))

