# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pydm.ui'
#
# Created: Mon Oct 10 13:18:51 2016
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(672, 112)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.panelSearchLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.panelSearchLineEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.panelSearchLineEdit.setObjectName("panelSearchLineEdit")
        self.horizontalLayout.addWidget(self.panelSearchLineEdit)
        self.goButton = QtGui.QPushButton(self.centralwidget)
        self.goButton.setFlat(False)
        self.goButton.setObjectName("goButton")
        self.horizontalLayout.addWidget(self.goButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.backButton = QtGui.QPushButton(self.centralwidget)
        self.backButton.setObjectName("backButton")
        self.horizontalLayout.addWidget(self.backButton)
        self.forwardButton = QtGui.QPushButton(self.centralwidget)
        self.forwardButton.setObjectName("forwardButton")
        self.horizontalLayout.addWidget(self.forwardButton)
        self.homeButton = QtGui.QPushButton(self.centralwidget)
        self.homeButton.setObjectName("homeButton")
        self.horizontalLayout.addWidget(self.homeButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 672, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionEdit_in_Designer = QtGui.QAction(MainWindow)
        self.actionEdit_in_Designer.setObjectName("actionEdit_in_Designer")
        self.actionAbout_DIM = QtGui.QAction(MainWindow)
        self.actionAbout_DIM.setEnabled(False)
        self.actionAbout_DIM.setObjectName("actionAbout_DIM")
        self.actionReload_Display = QtGui.QAction(MainWindow)
        self.actionReload_Display.setObjectName("actionReload_Display")
        self.actionIncrease_Font_Size = QtGui.QAction(MainWindow)
        self.actionIncrease_Font_Size.setObjectName("actionIncrease_Font_Size")
        self.actionDecrease_Font_Size = QtGui.QAction(MainWindow)
        self.actionDecrease_Font_Size.setObjectName("actionDecrease_Font_Size")
        self.menuFile.addAction(self.actionAbout_DIM)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionEdit_in_Designer)
        self.menuFile.addAction(self.actionReload_Display)
        self.menuView.addAction(self.actionIncrease_Font_Size)
        self.menuView.addAction(self.actionDecrease_Font_Size)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "PyDM Main Window", None, QtGui.QApplication.UnicodeUTF8))
        self.panelSearchLineEdit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Search for a display...", None, QtGui.QApplication.UnicodeUTF8))
        self.goButton.setText(QtGui.QApplication.translate("MainWindow", "Go", None, QtGui.QApplication.UnicodeUTF8))
        self.backButton.setText(QtGui.QApplication.translate("MainWindow", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.forwardButton.setText(QtGui.QApplication.translate("MainWindow", "Forward", None, QtGui.QApplication.UnicodeUTF8))
        self.homeButton.setText(QtGui.QApplication.translate("MainWindow", "Home", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEdit_in_Designer.setText(QtGui.QApplication.translate("MainWindow", "Edit in Designer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_DIM.setText(QtGui.QApplication.translate("MainWindow", "About PyDM", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReload_Display.setText(QtGui.QApplication.translate("MainWindow", "Reload Display", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReload_Display.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIncrease_Font_Size.setText(QtGui.QApplication.translate("MainWindow", "Increase Font Size", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIncrease_Font_Size.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+=", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDecrease_Font_Size.setText(QtGui.QApplication.translate("MainWindow", "Decrease Font Size", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDecrease_Font_Size.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+-", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

