# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'display.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(482, 416)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.pvLabel1 = QtWidgets.QLabel(self.centralwidget)
        self.pvLabel1.setAutoFillBackground(False)
        self.pvLabel1.setObjectName("pvLabel1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pvLabel1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.pvLabel2 = QtWidgets.QLabel(self.centralwidget)
        self.pvLabel2.setObjectName("pvLabel2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pvLabel2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.pvLabel3 = QtWidgets.QLabel(self.centralwidget)
        self.pvLabel3.setObjectName("pvLabel3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pvLabel3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.pvLabel4 = QtWidgets.QLabel(self.centralwidget)
        self.pvLabel4.setObjectName("pvLabel4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pvLabel4)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.pvLabel5 = QtWidgets.QLabel(self.centralwidget)
        self.pvLabel5.setObjectName("pvLabel5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pvLabel5)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.pvLabel6 = QtWidgets.QLabel(self.centralwidget)
        self.pvLabel6.setObjectName("pvLabel6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.pvLabel6)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.pvLabel7 = QtWidgets.QLabel(self.centralwidget)
        self.pvLabel7.setObjectName("pvLabel7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.pvLabel7)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.pvLabel8 = QtWidgets.QLabel(self.centralwidget)
        self.pvLabel8.setObjectName("pvLabel8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.pvLabel8)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.pvLabel9 = QtWidgets.QLabel(self.centralwidget)
        self.pvLabel9.setObjectName("pvLabel9")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.pvLabel9)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.pvLabel10 = QtWidgets.QLabel(self.centralwidget)
        self.pvLabel10.setObjectName("pvLabel10")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.pvLabel10)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 482, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Python Display Manager Proof-of-Concept"))
        self.label.setText(_translate("MainWindow", "BPMS:MATT:1:XTH"))
        self.pvLabel1.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "BPMS:MATT:2:XTH"))
        self.pvLabel2.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "BPMS:MATT:3:XTH"))
        self.pvLabel3.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "BPMS:MATT:4:XTH"))
        self.pvLabel4.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "BPMS:MATT:5:XTH"))
        self.pvLabel5.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "BPMS:MATT:6:XTH"))
        self.pvLabel6.setText(_translate("MainWindow", "TextLabel"))
        self.label_7.setText(_translate("MainWindow", "BPMS:MATT:7:XTH"))
        self.pvLabel7.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "BPMS:MATT:8:XTH"))
        self.pvLabel8.setText(_translate("MainWindow", "TextLabel"))
        self.label_9.setText(_translate("MainWindow", "BPMS:MATT:9:XTH"))
        self.pvLabel9.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "BPMS:MATT:10:XTH"))
        self.pvLabel10.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

