{% set package_name = "pydm" %}
{% set import_name = "pydm" %}
{% set version = load_file_regex(load_file=os.path.join(import_name, "_version.py"), regex_pattern=".*version = '(\S+)'").group(1) %}

package:
    name    : {{ package_name }}
    version : {{ version }}

source:
    path: ..

build:
  noarch: python
  entry_points:
    - pydm = pydm_launcher.main:main

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
    - setuptools_scm
    - pyqt =5
    - qtpy >=2.2.0
  run:
    - python >=3.9
    - six
    - numpy
    - scipy
    - pyepics
    - pyqt =5
    - pyqtgraph
    - qtpy >=2.2.0
    - entrypoints

test:
  imports:
    - pydm

about:
  home: https://github.com/slaclab/pydm
  license: SLAC Open
  license_family: OTHER
  license_file: LICENSE.md
  summary: 'Python Display Manager'
  description: |
    PyDM is a PyQt-based framework for building user interfaces for control systems.
    The goal is to provide a no-code, drag-and-drop system to make simple screens,
    as well as a straightforward Python framework to build complex applications.
  doc_url: https://slaclab.github.io/pydm/
  dev_url: https://github.com/slaclab/pydm
