# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'positioner.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(692, 355)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.desGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.desGroupBox.setObjectName("desGroupBox")
        self.formLayout = QtWidgets.QFormLayout(self.desGroupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.desGroupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.xPosTextEntry = QtWidgets.QLineEdit(self.desGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xPosTextEntry.sizePolicy().hasHeightForWidth())
        self.xPosTextEntry.setSizePolicy(sizePolicy)
        self.xPosTextEntry.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(13)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.xPosTextEntry.setFont(font)
        self.xPosTextEntry.setText("")
        self.xPosTextEntry.setProperty("channel", "MOTOR:1:VAL")
        self.xPosTextEntry.setObjectName("xPosTextEntry")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.xPosTextEntry)
        self.label_2 = QtWidgets.QLabel(self.desGroupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.yPosTextEntry = QtWidgets.QLineEdit(self.desGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yPosTextEntry.sizePolicy().hasHeightForWidth())
        self.yPosTextEntry.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(13)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.yPosTextEntry.setFont(font)
        self.yPosTextEntry.setText("")
        self.yPosTextEntry.setProperty("channel", "MOTOR:1:VAL")
        self.yPosTextEntry.setObjectName("yPosTextEntry")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.yPosTextEntry)
        self.label_3 = QtWidgets.QLabel(self.desGroupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.zPosTextEntry = QtWidgets.QLineEdit(self.desGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zPosTextEntry.sizePolicy().hasHeightForWidth())
        self.zPosTextEntry.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(13)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.zPosTextEntry.setFont(font)
        self.zPosTextEntry.setText("")
        self.zPosTextEntry.setProperty("channel", "MOTOR:1:VAL")
        self.zPosTextEntry.setObjectName("zPosTextEntry")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.zPosTextEntry)
        self.horizontalLayout.addWidget(self.desGroupBox)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.motor1DesLabel = QtWidgets.QLabel(self.groupBox)
        self.motor1DesLabel.setText("")
        self.motor1DesLabel.setObjectName("motor1DesLabel")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.motor1DesLabel)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.motor2DesLabel = QtWidgets.QLabel(self.groupBox)
        self.motor2DesLabel.setText("")
        self.motor2DesLabel.setObjectName("motor2DesLabel")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.motor2DesLabel)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.motor3DesLabel = QtWidgets.QLabel(self.groupBox)
        self.motor3DesLabel.setText("")
        self.motor3DesLabel.setObjectName("motor3DesLabel")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.motor3DesLabel)
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.desGroupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.desGroupBox_2.setObjectName("desGroupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.desGroupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.desGroupBox_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.desGroupBox_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.desGroupBox_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.motor1ReadbackLabel = QtWidgets.QLabel(self.desGroupBox_2)
        self.motor1ReadbackLabel.setObjectName("motor1ReadbackLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.motor1ReadbackLabel)
        self.motor2ReadbackLabel = QtWidgets.QLabel(self.desGroupBox_2)
        self.motor2ReadbackLabel.setObjectName("motor2ReadbackLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.motor2ReadbackLabel)
        self.motor3ReadbackLabel = QtWidgets.QLabel(self.desGroupBox_2)
        self.motor3ReadbackLabel.setObjectName("motor3ReadbackLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.motor3ReadbackLabel)
        self.horizontalLayout_2.addWidget(self.desGroupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 692, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Positioner Demo"))
        self.desGroupBox.setTitle(_translate("MainWindow", "Desired Position"))
        self.label.setText(_translate("MainWindow", "X Position (mm)"))
        self.xPosTextEntry.setPlaceholderText(_translate("MainWindow", "Enter Value"))
        self.label_2.setText(_translate("MainWindow", "Y Position (mm)"))
        self.yPosTextEntry.setPlaceholderText(_translate("MainWindow", "Enter Value"))
        self.label_3.setText(_translate("MainWindow", "Theta Position (mrad)"))
        self.zPosTextEntry.setPlaceholderText(_translate("MainWindow", "Enter Value"))
        self.groupBox.setTitle(_translate("MainWindow", "Desired Motor Values "))
        self.label_10.setText(_translate("MainWindow", "MOTOR:1"))
        self.label_11.setText(_translate("MainWindow", "MOTOR:2"))
        self.label_12.setText(_translate("MainWindow", "MOTOR:3"))
        self.pushButton.setText(_translate("MainWindow", "Move Motors To Desired Position"))
        self.desGroupBox_2.setTitle(_translate("MainWindow", "Motor Readback Values"))
        self.label_4.setText(_translate("MainWindow", "MOTOR:1:VAL"))
        self.label_5.setText(_translate("MainWindow", "MOTOR:2:VAL"))
        self.label_6.setText(_translate("MainWindow", "MOTOR:3:VAL"))
        self.motor1ReadbackLabel.setText(_translate("MainWindow", "Disconnected"))
        self.motor2ReadbackLabel.setText(_translate("MainWindow", "Disconnected"))
        self.motor3ReadbackLabel.setText(_translate("MainWindow", "Disconnected"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

