# This workflow will publish a new version of the documentation to the gh-pages branch

name: Publish Documentation

on:
  push:
    branches: [ "master" ]

# Required to push the built docs to the gh-pages branch
permissions:
  contents: write

jobs:
  deploy:
    if: ${{ github.repository == 'slaclab/pydm' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: conda-incubator/setup-miniconda@8ee1f361103df19b6f8c8655fd3967a8ecb162d5 # v4.0.1
        with:
          python-version: "3.12"
          miniforge-version: latest
          activate-environment: pydm-docs

      - name: Install python packages
        shell: bash -el {0}
        run: |
          mamba install pydm $(cat docs-requirements.txt)
      - name: Build Docs
        shell: bash -l {0}
        run: |
          pushd docs
          make html
          popd

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
